version: "3.6"

services:
  mqtt-server:
    image: ghcr.io/us-joet/everest-demo/mqtt-server:${TAG}
    platform: linux/x86_64
    logging:
      driver: none

  manager:
    image: ghcr.io/us-joet/everest-demo/manager:${TAG}
    platform: linux/x86_64
    depends_on:
      - mqtt-server
    environment:
      - MQTT_SERVER_ADDRESS=mqtt-server
    entrypoint: "sh ./build/run-scripts/run-sil-ocpp.sh"
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0

  ocpp-db:
    image: ghcr.io/us-joet/everest-demo/ocpp-db-compiled:0.0.1
    command: [ "--datadir", "/var/lib/mysql-no-volume" ]
    ports:
      - 13306:3306
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: ocpp-db
      MYSQL_USER: ocpp
      MYSQL_PASSWORD: ocpp

  steve:
    image: ghcr.io/us-joet/everest-demo/steve-configured:0.0.1
    ports:
      - 8180:8180
      - 8443:8443
    depends_on:
      - ocpp-db

  nodered:
    image: ghcr.io/us-joet/everest-demo/nodered:${TAG}
    depends_on:
      - mqtt-server
    ports:
      - 1880:1880
    environment:
      - MQTT_SERVER_ADDRESS=mqtt-server
      - FLOWS=/config/config-sil-two-evse-flow.json
